### ISSUE TITLE
Не проходят чеки github-script@0.2.0

### ISSUE THREAD

**Issue by futurelink** [developers-against-repressions/case-212#2345]
```
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/actions/github-script/0.2.0/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
##[error]Resource not accessible by integration
    at async eval (eval at main (/home/runner/work/_actions/actions/github-script/0.2.0/main.js:19:14), <anonymous>:24:3)
    at async main (/home/runner/work/_actions/actions/github-script/0.2.0/main.js:20:18) {
  name: 'HttpError',
  status: 403,
```
Что я делаю не так? Или отвалилась CI?

**Comment by ailinykh** [comment]
Да да. Это CI отвалился. Разбираемся с этим)

**Comment by futurelink** [comment]
Спасибо!
